name: GitHub Pages Deploy

on:
  push:
    branches:
      - lance-ecom

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build  # Update to match your build output directory
          token: ${{ secrets.GH_PAT }}
