name: Deployment

on:
  push:
    branches:
      - lance-ecom

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Verify Node.js version
        run: node --version 

      - name: Build Jekyll
        run: |
          bundle exec jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: _site
          token: ${{ secrets.GH_PAT }}
