name: CI/CD Pipeline

on:
  push:
    branches:
      - lance-com-app
  pull_request:
    branches:
      - lance-com-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npx eslint .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/lance-com-app'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to production
        env:
          NODE_ENV: production
        run: |
          # Add your deployment script/command here
          echo "Deploying application..."
          # Example: scp files to your server
          # scp -r . user@your-server:/path/to/deploy
