name: Deployment

on:
  push:
    branches:
      - lance-ecom

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify Node.js version
        run: node --version 

      # Add your deployment steps here
      - name: Deploy to production
        run: |
          echo "Deploying..."
          # Add your deployment script or commands here
