name: CI/CD Pipeline

on:
  push:
    branches:
      - lance-ecom
  pull_request:
    branches:
      - lance-ecom

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npx eslint .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/lance-ecom'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to production
        env:
          NODE_ENV: production
        run: |
          # Add your deployment script/command here
          echo "Deploying application..."
          # Example: scp files to your server
          # scp -r . user@your-server:/path/to/deploy
